### ISSUE TITLE
Crash on Join (most) multiplayer server

### ISSUE THREAD

**Issue by KRN-8** [Xeloboyo/PvP-Notifs#13]
Looks like the 2 places with "Vars.ui.chatfrag.addMessage(" are crashing now (likely EZ fix)
```
Version: steam build 126.3 (= latest steam build, also prolly last v6 build)
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64

rhino.EvaluatorException: 
Can't find method mindustry.ui.fragments.ChatFragment.addMessage(rhino.ConsString). (main.js#1153)
```
```
	at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
	at rhino.Context.reportRuntimeError(Context.java:830)
	at rhino.Context.reportRuntimeError(Context.java:876)
	at rhino.Context.reportRuntimeError1(Context.java:844)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:125)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.main_js_58._c_update_121(main.js:1153)
	at rhino.gen.main_js_58.call(main.js)
	at rhino.optimizer.OptRuntime.callName0(OptRuntime.java:61)
	at rhino.gen.main_js_58._c_anonymous_114(main.js:1113)
	at rhino.gen.main_js_58.call(main.js)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.main_js_58.call(main.js)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:524)
	at rhino.ContextFactory.call(ContextFactory.java:446)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.jdk18.VMBridge_jdk18.lambda$newInterfaceProxy$0(VMBridge_jdk18.java:100)
	at com.sun.proxy.$Proxy2.run(Unknown Source)
	at arc.Events.lambda$run$0(Events.java:17)
	at arc.Events.lambda$fire$1(Events.java:29)
	at arc.struct.Seq.each(Seq.java:200)
	at arc.Events.fire(Events.java:29)
	at arc.Events.fire(Events.java:25)
	at mindustry.core.Logic.update(Logic.java:362)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

**Comment by KRN-8** [comment]
ok i figured it out
you updated the (now Deprecated in v6) "chatfrag.addMessage(message, sender)" to the new v7 "chatfrag.addMessage(msg)"
soo it now crashes in v6

soo to Fix that atleast update the "mod.json" min game version to around the version this function got changed (i think it was v132)

(for now i made a fork of a fork that works in v6, anyone can have both versions installed now ;-) )
